import { StyleSheet } from "react-native";
import { COLOR, SIZE } from "../../constants/index";

const styles = StyleSheet.create({
    container:{
        flex: 1,
        backgroundColor:COLOR.lightWhite,
    },
    upperRow:{
        marginHorizontal:20,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        position:'absolute',
        top:SIZE.xxLarge,
        width:SIZE.width-44,
        zIndex:999
    },
    image:{
        aspectRatio:1,
        resizeMode:'cover'
    },
    details:{
        marginTop:-SIZE.large,
        backgroundColor:COLOR.lightWhite,
        width:SIZE.width,
        borderTopLeftRadius:SIZE.medium,
        borderTopRightRadius:SIZE.medium,
        paddingHorizontal:SIZE.medium,
    },
    titleRow:{
        paddingBottom:SIZE.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZE.width-44,
        top:20
    },
    title:{
        fontFamily:'bold',
        fontSize:SIZE.large
    },
    price:{
        padding:10,
        fontFamily:'semiBold',
        fontSize:SIZE.large
    },
    priceWrapper:{
        backgroundColor:COLOR.secondary,
        borderRadius:SIZE.large
    },
    ratingRow:{
        paddingBottom:SIZE.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZE.width-10,
        top:5,

    },
    rating:{
        top:SIZE.large,
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        marginRight:SIZE.large
    },
    ratingNumber:{
        color:COLOR.gray,
        fontFamily:'medium',
        paddingHorizontal:SIZE.xSmall
    },
    descriptionWrapper:{
        marginTop:SIZE.large*2,
        fontSize:SIZE.large
    },
    description:{
        fontFamily:'medium',
        fontSize:SIZE.large-2
    },
    descText:{
        fontFamily:'regular',
        fontSize:SIZE.small,
        textAlign:'justify',
        marginBottom:SIZE.small
    },
    location:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        backgroundColor: COLOR.secondary,
        padding:5,
        borderRadius:SIZE.large
    },
    cartRow:{
        paddingBottom:SIZE.small,
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        width:SIZE.width-20,
    },
    cartButton:{
        width:SIZE.width*0.7,
        backgroundColor:COLOR.black,
        padding:SIZE.small/2,
        borderRadius:SIZE.large,
    },
    cartTitle:{
        fontFamily:'semiBold',
        fontSize:SIZE.medium,
        color:COLOR.lightWhite,
        marginLeft:SIZE.small,
    },
    addCart:{
        width:37,
        height:37,
        borderRadius:50,
        margin:SIZE.small,
        backgroundColor:COLOR.black,
        alignItems:'center',
        justifyContent:'center'
    }
})

export default styles;